name: klay
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  
  flutter_lints: ^1.0.4
  cupertino_icons: ^1.0.4
  flutter_svg: ^1.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true


  assets:
    - assets/fonts/Tajawal-Bold.ttf
    - assets/fonts/Tajawal-Medium.ttf
    - assets/fonts/Tajawal-Regular.ttf
    - assets/images/intro_doctor1.svg
    - assets/images/intro_doctor2.svg
    - assets/images/intro_patient1.svg
    - assets/images/intro_patient2.svg
    - assets/images/logo.svg
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
